name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.2 
  native_device_orientation: ^2.1.0
  shared_preferences: ^2.5.5
  camera: ^0.11.0+2
  video_player: ^2.11.1
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tennis_ball.png
    - assets/lottie/rotate_guide.json
    - assets/lottie/tennis_ball.json
    - assets/markers/aruco_marker_0.png
    - assets/images/howto_step_01.png
    - assets/images/howto_step_02.png
    - assets/images/howto_step_03.png
    - assets/images/howto_step_04.png
    - assets/images/howto_step_05.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21